branch-defaults:
  default:
    environment: $ELASTIC_BEANSTALK_ENV
    group_suffix: null
deploy:
  artifact: www/Archive.zip
global:
  application_name: $ELASTIC_BEANSTALK_APP_NAME
  branch: null
  default_ec2_keyname: null
  default_platform: $ELASTIC_BEANSTALK_PLATFORM
  default_region: $AWS_REGION
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
